name: changes-requested

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running action..."
      - uses: luanpotter/changes-requested@v1
