name: changes-requested

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Running action..."
      - name: Changes Requested
        uses: luanpotter/changes-requested@master
