name: changes-requested

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: luanpotter/changes-requested@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          days-until-close: 0
          dry-run: true
